### ISSUE TITLE
Убрать из репозитория скрипты, которые можно подключать через менеджеры пакетов

### ISSUE THREAD

**Issue by tekord** [MrAnger/yii2-site-template#2]
Подключать через bower или npm. Причём следует иметь в виду, что:

1. В yii 2.1 будет выпилен плагин fxp для композера, и нам нужно привыкать работать с npm напрямую
2. bower умывает руки и на официальном сайте написали: "While Bower is maintained, we recommend yarn and webpack for new front-end projects!". То есть bower призывает задействовать что-то получем чем bower.

**Comment by MrAnger** [comment]
https://asset-packagist.org
решил проблему
https://www.yiiframework.com/doc/guide/2.0/ru/structure-assets
