### ISSUE TITLE
Удалить неподдерживаемые пакеты

### ISSUE THREAD

**Issue by tekord** [MrAnger/yii2-site-template#3]
Пакет yiisoft/yii2-codeception больше не поддерживается и считается DEPRECATED.

Обновить версию до актуальной:
"yiisoft/yii2": ">=2.0.6",

**Comment by tekord** [comment]
Вместо  yiisoft/yii2-codeception:

    "codeception/base": "^2.2.3",
    "codeception/verify": "~0.3.1",

**Comment by MrAnger** [comment]
Готово https://github.com/MrAnger/yii2-site-template/blob/master/composer.json
